### ISSUE TITLE
Progressive Loading not working.

### ISSUE THREAD

**Issue by QuantumRevenger** [UprootLabs/poly-flif#35] opened 2017-03-27 17:43 UTC
When loading a progressive image e.g

`<canvas id="draw" data-polyflif-src="http://res.cloudinary.com/jon/fl_progressive,fl_lossy,q_25/kodim05.flif"></canvas>`

The whole file is loaded before being displayed rather than progressively.

**Comment by hrj** [comment] 2017-03-27 17:54
Yup, this is not yet done. See #13 

It's quite a tricky thing to do, because JS is single threaded and the callbacks from FLIF are not asynchronous.

There are multiple approaches possible, such as configuring emscripten to allow asynchronous callbacks, or modifying the FLIF decoder itself to allow decoding to be continued.

closing this as duplicate of #13.

**Closed as completed by hrj** 2017-03-27 17:54 UTC
