### ISSUE TITLE
animation stays when viewing still

### ISSUE THREAD

**Issue by jonsneyers** [UprootLabs/poly-flif#11] opened 2015-10-16 19:25 UTC
If you first view an animation and then a still image, the animation remains visible.

**Comment by hrj** [comment] 2015-10-17 03:44
​Is this reproducible always? I have seen it happen just once during
testing.

​Which browser & version?

**Comment by jonsneyers** [comment] 2015-10-17 06:58
Chrome OS
Version 45.0.2454.98
Platform 7262.57.0 (Official Build) stable-channel nyan_big
Firmware Google_Nyan_Big.5771.63.0

**Comment by ayurmedia** [comment] 2015-10-26 00:01
![flif-animation-and-image](https://cloud.githubusercontent.com/assets/1746990/10719064/2f37615e-7b81-11e5-8cbb-03fa30b1a30c.png)
Can also Confirm, Chrome , Win10. If you load animation and later a picture, the animation keeps staying on top of the image. Reproduce, load animation "pyani" then picture "monkey" result see screenshot.

**Comment by hrj** [comment] 2015-10-26 05:51
> Reproduce, load animation "pyani" then picture "monkey" result see screenshot.

Thanks! I still can't repro this, but will try to analyse that path.

**Comment by hrj** [comment] 2016-06-11 12:30
I noticed a similar issue while coding up the new API, and fixed it.

Please refresh the demo page and let me know if the issue is still present.

Closing optimistically.

**Closed as completed by hrj** 2016-06-11 12:30 UTC
Labels: bug, demo
